<a href="https://colab.research.google.com/github/Mukherjee-Swastika/DATA-SCIENCE-/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [76]:
import numpy as np
import pandas as pd
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'1':10,'2':20,'3':30}

In [77]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [78]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [79]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [80]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

In [81]:
import numpy as np
import pandas as pd

In [82]:
data = {
    'Name':['pitu','diya','mithu','deep'],
    'Age':['28','34','29','42'],
    'City':['A','B','C','D'],
    'Salary':['65000','70000','62000','85000']
}
df=pd.DataFrame(data)

In [83]:
df

    Name Age City Salary
0   pitu  28    A  65000
1   diya  34    B  70000
2  mithu  29    C  62000
3   deep  42    D  85000

In [84]:
data_list = [
    ['pitu','28','A','65000'],
    ['diya','34','B','42000'],
    ['mithu','29','C','62000'],
    ['deep','42','D','85000']
]
df2 = pd.DataFrame(data_list)

In [85]:
df2

       0   1  2      3
0   pitu  28  A  65000
1   diya  34  B  42000
2  mithu  29  C  62000
3   deep  42  D  85000

In [86]:
data_list = [
    ['pitu','28','A','65000'],
    ['diya','34','B','42000'],
    ['mithu','29','C','62000'],
    ['deep','42','D','85000']
]
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns = columns)

In [87]:
df2

    Name Age City Salary
0   pitu  28    A  65000
1   diya  34    B  42000
2  mithu  29    C  62000
3   deep  42    D  85000

**SELECTING COLUMN**

In [88]:
df2[["Name","City"]]

    Name City
0   pitu    A
1   diya    B
2  mithu    C
3   deep    D

**CREATING A NEW COLUMN**

In [89]:
df2["Designation"] = ["Doctor","Eng.","Doctor","Eng."]
df2

    Name Age City Salary Designation
0   pitu  28    A  65000      Doctor
1   diya  34    B  42000        Eng.
2  mithu  29    C  62000      Doctor
3   deep  42    D  85000        Eng.

**REMOVE A COLUMN**

In [90]:
df2.drop('Designation',axis = 1)

    Name Age City Salary
0   pitu  28    A  65000
1   diya  34    B  42000
2  mithu  29    C  62000
3   deep  42    D  85000

In [91]:
df2

    Name Age City Salary Designation
0   pitu  28    A  65000      Doctor
1   diya  34    B  42000        Eng.
2  mithu  29    C  62000      Doctor
3   deep  42    D  85000        Eng.

In [92]:
df2.drop(["City","Salary"],axis = 1)

    Name Age Designation
0   pitu  28      Doctor
1   diya  34        Eng.
2  mithu  29      Doctor
3   deep  42        Eng.

In [93]:
df2

    Name Age City Salary Designation
0   pitu  28    A  65000      Doctor
1   diya  34    B  42000        Eng.
2  mithu  29    C  62000      Doctor
3   deep  42    D  85000        Eng.

**SELECTING ROWS**

In [94]:
df2.iloc[[3]]

   Name Age City Salary Designation
3  deep  42    D  85000        Eng.

**SELECTING SUBSETS OF ROWS AND COLUMNS**

In [95]:
df.loc[[2,3]][["Name","Age"]]

    Name Age
2  mithu  29
3   deep  42

Only those whose age os above 30

In [96]:
df2[pd.to_numeric(df2["Age"]) > 30]

   Name Age City Salary Designation
1  diya  34    B  42000        Eng.
3  deep  42    D  85000        Eng.

above 30 and city must be D

In [97]:
df2[(pd.to_numeric(df2["Age"]) > 30) & (df2["City"] == 'D')]

   Name Age City Salary Designation
3  deep  42    D  85000        Eng.

**FINDING MISSING DATA**

In [98]:
data = {
    'A':[1,2,np.nan,4,5],
    'B':[1,2,3,4,5],
    'C':[1,2,3,np.nan,np.nan],
    'D':[1,np.nan,np.nan,np.nan,5]
}
df = pd.DataFrame(data)

In [99]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [100]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [101]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [102]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [103]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [104]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [105]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [106]:
df.dropna(thresh = 3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [107]:
df.fillna(0) #there should be atleast 3 non-bull values

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [108]:
values = {'A':0,'B':100,'C':300,'D':400}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [109]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

***MergingJoiningConcatination***

---

Merging 2 dataframes

In [110]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [111]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [112]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [113]:
pd.merge(employees,salaries,on='employee_id',how ='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [114]:
pd.merge(employees,salaries,on='employee_id',how ='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [115]:
pd.merge(employees,salaries,on='employee_id',how ='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [116]:
pd.merge(employees,salaries,on='employee_id',how ='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [117]:
pd.merge(employees,salaries,on='employee_id',how ='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

In [118]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [119]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [120]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [121]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [122]:
pd.concat([df1,df2],axis= 1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

**joining 2 dataframes**

In [123]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [124]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [125]:
df2

   score
2     85
3     90
4     75

In [126]:
df1.join(df2,how = 'outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [127]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

In [128]:
pd.concat([df1,df2])

      name  score
1    Alice    NaN
2      Bob    NaN
3  Charlie    NaN
2      NaN   85.0
3      NaN   90.0
4      NaN   75.0

**GroupByAggregation**

In [129]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [130]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [131]:
#Group by Category
cat = df.groupby('Category')
cat
for i,v in cat:
    print(i)
    print(v)

A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07
B
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

In [132]:
#Group by Category and calculate the sum of Sales
cat = df.groupby('Category') ['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [133]:
#Group by Store and calculate the sum of Sales
cat = df.groupby('Store') ['Sales'].sum()
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

**Aggregation**

In [134]:
df['Sales'].mean()
"""mean median min max count std """

'mean median min max count std '

In [135]:
df['Sales'].agg(['sum', 'mean', 'min', 'max', 'count', 'std', 'median'])

sum       1500.000000
mean       187.500000
min        100.000000
max        300.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64

**Pivot Tables**

In [136]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    914     66   John  January      Q1
1  2023-01-02       B   West    507     34   Mary  January      Q1
2  2023-01-03       C  North    575     74    Bob  January      Q1
3  2023-01-04       D  South    487     19  Alice  January      Q1
4  2023-01-05       A   East    469     16   John  January      Q1
5  2023-01-06       B   West    547     15   Mary  January      Q1
6  2023-01-07       C  North    859     10    Bob  January      Q1
7  2023-01-08       D  South    785     81  Alice  January      Q1
8  2023-01-09       A   East    493     58   John  January      Q1
9  2023-01-10       B   West    540     54   Mary  January      Q1
10 2023-01-11       C  North    227     37    Bob  January      Q1
11 2023-01-12       D  South    847     99  Alice  January      Q1
12 2023-01-13       A   East    522     10   John  January      Q1
13 2023-01-14       B   West    726     92   Mary  January      Q1
14 2023-01-15       C  North    405     36    Bob  January      Q1
15 2023-01-16       D  South    788     26  Alice  January      Q1
16 2023-01-17       A   East    681     37   John  January      Q1
17 2023-01-18       B   West    749     96   Mary  January      Q1
18 2023-01-19       C  North    156     88    Bob  January      Q1
19 2023-01-20       D  South    925     44  Alice  January      Q1

In [137]:
#here by default mean is happening
pd.pivot_table(df,values = "Sales",index = 'Region',columns="Product")

Product      A      B      C      D
Region
East     615.8    NaN    NaN    NaN
North      NaN    NaN  444.4    NaN
South      NaN    NaN    NaN  766.4
West       NaN  613.8    NaN    NaN

In [138]:
pd.pivot_table(df,values = "Sales",index = 'Region',columns="Product",aggfunc = 'median')

Product      A      B      C      D
Region
East     522.0    NaN    NaN    NaN
North      NaN    NaN  405.0    NaN
South      NaN    NaN    NaN  788.0
West       NaN  547.0    NaN    NaN

In [139]:
pivot2 = pd.pivot_table(df, values=['Sales', 'Units'], index='Region', columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     615.8    NaN    NaN    NaN  37.4   NaN   NaN   NaN
North      NaN    NaN  444.4    NaN   NaN   NaN  49.0   NaN
South      NaN    NaN    NaN  766.4   NaN   NaN   NaN  53.8
West       NaN  613.8    NaN    NaN   NaN  58.2   NaN   NaN

**Cross Tabs**

In [140]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

**DataFrames Basic Operations**

In [141]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [142]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [143]:
df1.shape

(5, 3)

In [144]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [145]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [146]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [147]:
df1['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

**DataFrames Applying Functions**

In [148]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [149]:
df1['D'] = df1["B"].apply(lambda x : x**2)

In [150]:
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500